/**
 * `npm run sync:sheet` — copy the drawn artwork into the app.
 *
 * `art/walder.json` is the artist's file: it is regenerated by `art/frames.mjs`
 * whenever the pose or the palettes change, and it lives outside `src/` because
 * the art pipeline (and only the art pipeline) writes it. The app imports
 * `src/sprites/walder.json`, which is a *validated copy* made by this script.
 *
 * Why a copy at all, rather than importing across the folder boundary:
 *
 *  - **A gate.** The sheet is hand-authored data. This is the one place it is
 *    checked before it can reach the app, against both `validateSheet` (rows
 *    match their box, every letter resolves in every palette, every animation
 *    names frames that exist) and `requireSheetContract` (the names the code
 *    hard-codes). A sheet that fails is reported here, where
 *    the artist can still fix it, and is *not* copied — so a broken regeneration
 *    cannot replace working art in the app.
 *  - **The bundle.** `src/sprites/walder.json` is a static import, so
 *    electron-vite embeds it in `out/main/index.js` and it works identically from
 *    a packaged asar with no file reading at runtime.
 *
 * Runs before `dev`, `build` and `build:dist` via npm's `pre*` hooks, so the app
 * always draws the latest approved art without anyone having to remember a step.
 *
 * Failure is loud: a message naming the exact frame, row and column at fault, and
 * exit code 1, which stops the build that invoked it.
 */
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join, relative } from 'node:path';
import { validateSheet, SpriteSheetError, type SpriteSheet } from '../src/sprites/types';
import { requireSheetContract } from '../src/sprites/contract';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const SOURCE = join(root, 'art', 'walder.json');
const DEST = join(root, 'src', 'sprites', 'walder.json');

/**
 * What is written to `src/sprites/walder.json` when there is no art to copy.
 *
 * It exists so the static import in `src/main/sheet.ts` always resolves: a
 * missing file is a *bundler* error ("could not resolve ./walder.json"), which
 * for the owner is an incomprehensible wall of build output, while an empty sheet
 * is a case `loadSheet` handles by warning and drawing the placeholder dog. The
 * exit code below still fails the build that asked for the sync — this only
 * decides *how* a later build fails if someone runs one anyway.
 */
const STUB = '{}\n';

function fail(message: string): never {
  console.error(`\nsync-sheet: ${message}\n`);
  process.exit(1);
}

function rel(path: string): string {
  return relative(root, path);
}

/** Read and parse the artist's file, or exit 1 saying why. */
function readSource(): { text: string; json: unknown } {
  let text: string;
  try {
    text = readFileSync(SOURCE, 'utf8');
  } catch {
    // No art at all. Make sure the app can still be built (with the placeholder)
    // before failing, so the owner gets a warning and a dog rather than a
    // rollup resolution error.
    if (!existsSync(DEST)) {
      mkdirSync(dirname(DEST), { recursive: true });
      writeFileSync(DEST, STUB);
      console.error(`sync-sheet: wrote an empty ${rel(DEST)} so the app can still build`);
    }
    return fail(
      `${rel(SOURCE)} does not exist.\n` +
        `  The artwork is generated by the art pipeline:  node art/frames.mjs\n` +
        `  Until it is there the app draws the placeholder sprite.`
    );
  }

  try {
    return { text, json: JSON.parse(text) as unknown };
  } catch (error) {
    return fail(
      `${rel(SOURCE)} is not valid JSON.\n  ${error instanceof Error ? error.message : String(error)}`
    );
  }
}

/** Validate, or exit 1 with the validator's own message. */
function check(json: unknown): SpriteSheet {
  try {
    const sheet = validateSheet(json);
    requireSheetContract(sheet);
    return sheet;
  } catch (error) {
    if (error instanceof SpriteSheetError) {
      return fail(
        `${rel(SOURCE)} did not pass validation.\n  ${error.message}\n\n` +
          `  ${rel(DEST)} was left as it was — the app keeps drawing the last good art.`
      );
    }
    throw error;
  }
}

/** One line per thing the owner might want to see changed. */
function summarise(sheet: SpriteSheet): void {
  const boxes = Object.entries(sheet.boxes)
    .map(([name, [w, h]]) => `${name} ${w}x${h}`)
    .join(', ');
  const oneShots = Object.values(sheet.animations).filter((a) => !a.loop).length;
  const holds = Object.entries(sheet.animations)
    .filter(([, a]) => a.hold)
    .map(([name]) => name);

  console.log(`  frames      ${Object.keys(sheet.frames).length}`);
  console.log(
    `  animations  ${Object.keys(sheet.animations).length} ` +
      `(${oneShots} one-shot${oneShots === 1 ? '' : 's'}` +
      `${holds.length > 0 ? `, holding: ${holds.join(', ')}` : ''})`
  );
  console.log(`  palettes    ${Object.keys(sheet.palettes).join(', ')}`);
  console.log(`  boxes       ${boxes}`);
}

const { text: source, json } = readSource();
const sheet = check(json);

// Byte-identical copy rather than a re-serialisation: the two files should be
// diffable against each other, and a formatting change here would show up as a
// whole-file diff on every sync.
const unchanged = existsSync(DEST) && readFileSync(DEST, 'utf8') === source;
if (unchanged) {
  console.log(`sync-sheet: ${rel(DEST)} is already up to date`);
} else {
  mkdirSync(dirname(DEST), { recursive: true });
  writeFileSync(DEST, source);
  console.log(`sync-sheet: ${rel(SOURCE)} -> ${rel(DEST)} (${source.length} bytes)`);
}
summarise(sheet);
